spring.application.name=Project_CuoiKy_CongNghePhanMem_OOSE

# M?c ??nh khi ch?y local (không có bi?n môi tr??ng)
spring.profiles.active=dev

# C?u hình chung (dùng cho c? dev và prod)
server.port=8080
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl