use hotel;
INSERT INTO Beds (bedName, capacity) VALUES
                                         ('Single', 1),
                                         ('Double', 2),
                                         ('Queen', 2),
                                         ('King', 2),
                                         ('Twin', 1),
                                         ('Super King', 2),
                                         ('Sofa Bed', 2),
                                         ('Bunk Bed (2 tầng)', 4),
                                         ('Extra Bed (gấp gọn)', 1);
INSERT INTO MembershipTier (tierName, minPoint, discountRate, benefits) VALUES
                                                                            ('Bronze',      0,     0.00, 'Giá gốc, hỗ trợ cơ bản'),
                                                                            ('Silver',    800,     0.05, 'Giảm 5%, ưu tiên check-in 15 phút'),
                                                                            ('Gold',     2500,     0.10, 'Giảm 10%, check-out muộn đến 14:00, nước uống chào mừng'),
                                                                            ('Platinum', 6000,     0.15, 'Giảm 15%, nâng hạng phòng miễn phí (nếu có), check-out muộn đến 16:00, quà tặng chào mừng');
INSERT INTO RoomTypes (typeName, priceRoom, occupancy) VALUES
                                                           ('Basic',         680000, 2),
                                                           ('Superior',     1050000, 3),
                                                           ('Deluxe',       1480000, 3),
                                                           ('Royal',        2450000, 4),
                                                           ('Junior Suite', 3850000, 4),
                                                           ('Family Suite', 4200000, 6);
INSERT INTO RoomTypeBeds (quantity, typeID, bedID) VALUES
                                                       (2, 1, 1),   -- Basic: 2 Single
                                                       (1, 1, 2),   -- Basic: 1 Double
                                                       (1, 2, 3),   -- Superior: 1 Queen
                                                       (1, 2, 7),   -- Superior: + Sofa bed
                                                       (1, 3, 4),   -- Deluxe: 1 King
                                                       (2, 3, 3),   -- Deluxe: 2 Queen
                                                       (1, 4, 6),   -- Royal: 1 Super King
                                                       (1, 4, 7),   -- Royal: + Sofa bed
                                                       (1, 5, 6),   -- Junior Suite: Super King
                                                       (1, 5, 2),   -- Junior Suite: + Double
                                                       (1, 6, 4),   -- Family Suite: 1 King
                                                       (2, 6, 1),   -- Family Suite: 2 Single
                                                       (1, 6, 7);   -- Family Suite: + Sofa bed
INSERT INTO Rooms (roomNumber, status, description, typeID) VALUES
                                                                ('B101', 'available', 'View phố, yên tĩnh', 1),
                                                                ('B102', 'available', 'View phố', 1),
                                                                ('B103', 'maintenance', 'Đang sửa điều hòa', 1),
                                                                ('B104', 'available', '', 1),
                                                                ('B105', 'available', '', 1),
                                                                ('B106', 'available', '', 1),
                                                                ('B107', 'available', '', 1),
                                                                ('B108', 'available', '', 1),
                                                                ('B109', 'available', '', 1),
                                                                ('B110', 'available', '', 1),
                                                                ('B201', 'available', '', 1),
                                                                ('B202', 'available', '', 1),
                                                                ('B203', 'available', '', 1),
                                                                ('B204', 'available', '', 1),
                                                                ('B205', 'available', '', 1),
                                                                ('B206', 'available', '', 1),
                                                                ('B207', 'available', '', 1),
                                                                ('B208', 'available', '', 1),
                                                                ('B209', 'available', '', 1),
                                                                ('B210', 'available', '', 1),
                                                                ('B301', 'available', '', 1),
                                                                ('B302', 'available', '', 1),
                                                                ('B303', 'available', '', 1),
                                                                ('B304', 'available', '', 1),
                                                                ('B305', 'available', '', 1),
                                                                ('B306', 'available', '', 1),
                                                                ('B307', 'available', '', 1),
                                                                ('B308', 'available', '', 1),
                                                                ('B309', 'available', '', 1),
                                                                ('B310', 'inactive', 'Ngừng kinh doanh tạm thời', 1),
                                                                ('B401', 'available', '', 1),
                                                                ('B402', 'available', '', 1),
                                                                ('B403', 'available', '', 1),
                                                                ('B404', 'available', '', 1),
                                                                ('B405', 'available', '', 1),
                                                                ('B406', 'available', '', 1),
                                                                ('B407', 'available', '', 1),
                                                                ('B408', 'available', '', 1),
                                                                ('B409', 'available', '', 1),
                                                                ('B410', 'available', '', 1),
                                                                ('B501', 'available', '', 1),
                                                                ('B502', 'available', '', 1),
                                                                ('B503', 'available', '', 1),
                                                                ('B504', 'available', '', 1),
                                                                ('B505', 'available', '', 1),
                                                                ('S601', 'available', 'View sông, ban công nhỏ', 2),
                                                                ('S602', 'available', 'View sông', 2),
                                                                ('S603', 'maintenance', 'Sửa cửa sổ', 2),
                                                                ('S604', 'available', '', 2),
                                                                ('S605', 'available', '', 2),
                                                                ('S606', 'available', '', 2),
                                                                ('S607', 'available', '', 2),
                                                                ('S608', 'available', '', 2),
                                                                ('S609', 'available', '', 2),
                                                                ('S610', 'available', '', 2),
                                                                ('S701', 'available', '', 2),
                                                                ('S702', 'available', '', 2),
                                                                ('S703', 'available', '', 2),
                                                                ('S704', 'available', '', 2),
                                                                ('S705', 'maintenance', 'Sửa hệ thống điện', 2),
                                                                ('S706', 'available', '', 2),
                                                                ('S707', 'available', '', 2),
                                                                ('S708', 'available', '', 2),
                                                                ('S709', 'available', '', 2),
                                                                ('S710', 'available', '', 2),
                                                                ('S801', 'available', '', 2),
                                                                ('S802', 'available', '', 2),
                                                                ('S803', 'available', '', 2),
                                                                ('S804', 'available', '', 2),
                                                                ('S805', 'available', '', 2),
                                                                ('D901', 'available', 'Ban công lớn, view thành phố', 3),
                                                                ('D902', 'available', 'View thành phố', 3),
                                                                ('D903', 'available', '', 3),
                                                                ('D904', 'available', '', 3),
                                                                ('D905', 'available', '', 3),
                                                                ('D906', 'available', '', 3),
                                                                ('D907', 'available', '', 3),
                                                                ('D908', 'available', '', 3),
                                                                ('D909', 'available', '', 3),
                                                                ('D910', 'available', '', 3),
                                                                ('D1001', 'available', '', 3),
                                                                ('D1002', 'available', '', 3),
                                                                ('D1003', 'available', '', 3),
                                                                ('D1004', 'available', '', 3),
                                                                ('D1005', 'available', '', 3),
                                                                ('D1101', 'available', '', 3),
                                                                ('D1102', 'available', '', 3),
                                                                ('D1103', 'available', '', 3),
                                                                ('D1104', 'available', '', 3),
                                                                ('D1105', 'maintenance', 'Thay thảm sàn', 3),
                                                                ('R1201', 'available', 'Royal góc – view panorama', 4),
                                                                ('R1202', 'available', 'Royal trung tâm', 4),
                                                                ('R1203', 'available', '', 4),
                                                                ('R1204', 'available', '', 4),
                                                                ('R1301', 'available', '', 4),
                                                                ('R1302', 'available', '', 4),
                                                                ('R1303', 'available', '', 4),
                                                                ('R1304', 'available', '', 4),
                                                                ('R1401', 'available', '', 4),
                                                                ('R1402', 'available', '', 4),
                                                                ('JS1501', 'available', 'Junior Suite – phòng khách riêng', 5),
                                                                ('JS1502', 'available', '', 5),
                                                                ('JS1503', 'available', '', 5),
                                                                ('JS1504', 'available', '', 5),
                                                                ('FS1601', 'available', 'Family Suite – 2 phòng ngủ', 6),
                                                                ('FS1602', 'available', '', 6),
                                                                ('FS1603', 'available', '', 6),
                                                                ('FS1604', 'available', '', 6),
                                                                ('FS1605', 'inactive', 'Đang cải tạo', 6),
                                                                ('B111', 'available', '', 1),
                                                                ('B112', 'available', '', 1),
                                                                ('B113', 'available', '', 1),
                                                                ('B114', 'available', '', 1),
                                                                ('B115', 'available', '', 1),
                                                                ('B116', 'available', '', 1),
                                                                ('B117', 'available', '', 1),
                                                                ('B118', 'available', '', 1),
                                                                ('B119', 'available', '', 1),
                                                                ('B120', 'available', '', 1),
                                                                ('S611', 'available', '', 2),
                                                                ('S612', 'available', '', 2),
                                                                ('S613', 'available', '', 2),
                                                                ('S614', 'available', '', 2),
                                                                ('S615', 'available', '', 2),
                                                                ('D906', 'available', '', 3),
                                                                ('D907', 'available', '', 3),
                                                                ('D908', 'available', '', 3),
                                                                ('D909', 'available', '', 3),
                                                                ('D910', 'available', '', 3),
                                                                ('R1205', 'available', '', 4),
                                                                ('R1206', 'available', '', 4),
                                                                ('JS1505', 'available', '', 5),
                                                                ('FS1606', 'available', '', 6),
                                                                ('FS1607', 'available', '', 6),
                                                                ('B121', 'available', '', 1),
                                                                ('B122', 'available', '', 1),
                                                                ('B123', 'available', '', 1),
                                                                ('B124', 'available', '', 1),
                                                                ('B125', 'available', '', 1),
                                                                ('S616', 'available', '', 2),
                                                                ('S617', 'available', '', 2),
                                                                ('S618', 'available', '', 2),
                                                                ('D911', 'available', '', 3),
                                                                ('D912', 'available', '', 3),
                                                                ('R1207', 'available', '', 4),
                                                                ('R1208', 'available', '', 4);